---
title: "mod5_script"
output: html_document
date: "2025-05-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


## Libraries

```{r, echo=FALSE}
library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(stringr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(tibble, quietly = TRUE)
library(sf, quietly = TRUE)
library(here, quietly = TRUE)
library(janitor, quietly = TRUE)
library(sfislands, quietly = TRUE)
library(sfdep, quietly = TRUE)
library(rmapshaper, quietly = TRUE)
library(janitor, quietly = TRUE)

library(brms, quietly = TRUE)
library(rstan, quietly = TRUE)
library(geostan) # for prep_icar_data() function

set.seed(123)
```

## Data preparation

### Voting data 2017-2024

```{r, echo=FALSE}
custom_palette <- c("lab"="#E4003B",
                    "con"="#0087DC",
                    "ld"="#FAA61A",
                    # "ruk"="#12B6CF",
                    "ruk"="darkblue", # this gives better separation than suggested colour
                    "brx"="darkblue", 
                    "ukip"="darkblue",
                    "ind"="#8C0064",
                    "green"="#4BA663",
                    "pc"="#005B54",
                    "spk"="#DCDCDC",
                    "other"="gray20")

# constituencies in 2017 and 2019
constituencies19 <- st_read(here("data","boundaries","Westminster_Parliamentary_Constituencies_Dec_2019_Boundaries_UK_BFE_2022_5896292250094173431.geojson"), quiet = TRUE) |> 
  select(pcon19cd,pcon19nm,geometry) |> 
  rename(con_name = pcon19nm,
         con_code = pcon19cd) |> 
  ms_simplify() |> 
  filter(str_detect(con_code,"E")) # only England

# projection data to 2024
all_changes <- readxl::read_xlsx(here("data","boundaries","Boundary_changes_data_file.xlsx"), 
                                 sheet = 3, skip = 1)

projection_df <- all_changes |> 
  select(1:4,9,11) |> 
  rename(prop_old_in_new = `Percentage of old constituency in this segment (population) [notes 1 and 2]`)

```


```{r, echo=FALSE}

# 2017 votes
votes17 <- read.csv(here("data","results","HoC-GE2017-results-by-constituency.csv")) |> 
  clean_names() |> 
  left_join(constituencies19 |> select(con_code,geometry),
            by = c("ons_id"="con_code")) |> 
  filter(country_name == "England") |>  # only England
  rename(con_code = ons_id) |> 
  mutate(other = green + all_other_candidates) |> 
  rename(ruk = ukip) |> 
  select(con_code,constituency_name,region_name,majority,valid_votes,con,lab,ld,ruk,other,geometry) |> 
  st_as_sf()

# 2017 votes projected to 2024 constituencies
votes17proj <- votes17 |> 
  select(con_code,majority,valid_votes,con,lab,ld,ruk,other) |> 
  st_drop_geometry() |> 
  pivot_longer("majority":"other") |> 
  left_join(projection_df,
            by = c("con_code"="Current constituency code")) |> 
  mutate(value = prop_old_in_new * value) |> 
  select(name,value,`New constituency name`,`New constituency code`) |> 
  mutate(name = factor(name,
                       levels = c("con","lab","ld","ruk","other","valid_votes","majority"))) |> 
  rename(constituency_name = `New constituency name`, 
         con_code = `New constituency code`) |> 
  group_by(con_code, name) |> 
  summarise(value = sum(value) |> round()) |> 
  pivot_wider(names_from = "name",values_from = "value") |> 
  rowwise() |> 
  mutate(
    first_party17 = colnames(across(con:other))[which.max(c_across(con:other))], 
    second_party17 = colnames(across(con:other))[order(-c_across(con:other))[2]], 
    third_party17 = colnames(across(con:other))[order(-c_across(con:other))[3]]
  ) |> 
  ungroup() |> 
  rename(con17 = con,
         lab17 = lab,
         ld17 = ld,
         ruk17 = ruk,
         other17 = other,
         valid_votes17 = valid_votes,
         majority17 = majority) |> 
  mutate(con17_pct = 100*con17/valid_votes17,
         lab17_pct = 100*lab17/valid_votes17,
         ld17_pct = 100*ld17/valid_votes17,
         ruk17_pct = 100*ruk17/valid_votes17,
         other17_pct = 100*other17/valid_votes17)


# 2019 votes
votes19 <- read.csv(here("data","results","HoC-GE2019-results-by-constituency.csv")) |> 
  clean_names() |> 
  left_join(constituencies19 |> select(con_code,geometry),
            by = c("ons_id"="con_code")) |> 
  filter(country_name == "England") |> # only England
  rename(con_code = ons_id) |> 
  mutate(other = green + all_other_candidates) |> 
  rename(ruk = brx) |> 
  select(con_code,constituency_name,region_name,majority,valid_votes,first_party,second_party,con,lab,ld,ruk,other,geometry) |> 
  st_as_sf()

# 2019 votes projected to 2024 constituencies
votes19proj <- votes19 |> 
  select(con_code,majority,valid_votes,con,lab,ld,ruk,other) |> 
  st_drop_geometry() |> 
  pivot_longer("majority":"other") |> 
  left_join(projection_df,
            by = c("con_code"="Current constituency code")) |> 
  mutate(value = prop_old_in_new * value) |> 
  select(name,value,`New constituency name`,`New constituency code`) |> 
  mutate(name = factor(name,
                       levels = c("con","lab","ld","ruk","other","valid_votes","majority"))) |> 
  rename(constituency_name = `New constituency name`, 
         con_code = `New constituency code`) |> 
  group_by(con_code, name) |> 
  summarise(value = sum(value) |> round()) |> 
  pivot_wider(names_from = "name",values_from = "value") |> 
  rowwise() |> 
  mutate(
    first_party19 = colnames(across(con:other))[which.max(c_across(con:other))], 
    second_party19 = colnames(across(con:other))[order(-c_across(con:other))[2]], 
    third_party19 = colnames(across(con:other))[order(-c_across(con:other))[3]]
  ) |> 
  ungroup() |> 
  rename(con19 = con,
         lab19 = lab,
         ld19 = ld,
         ruk19 = ruk,
         other19 = other,
         valid_votes19 = valid_votes,
         majority19 = majority) |> 
  mutate(con19_pct = 100*con19/valid_votes19,
         lab19_pct = 100*lab19/valid_votes19,
         ld19_pct = 100*ld19/valid_votes19,
         ruk19_pct = 100*ruk19/valid_votes19,
         other19_pct = 100*other19/valid_votes19)


## Boundaries for constituencies and regions 2024
constituencies24 <- st_read(here("data","boundaries","geoConstituencies.json"), quiet = TRUE) |> 
  st_make_valid() |> 
  select(PCON24CD,PCON24NM,name3,regionNM,geometry) |> 
  rename(con_name = PCON24NM,
         con_code = PCON24CD,
         reg_name = regionNM,
         con_abb = name3) |> 
  filter(!reg_name %in% c("Scotland","Wales","Northern Ireland"))

regions <- constituencies24 |> 
  ms_dissolve("reg_name") |> 
  mutate(reg_name = case_when(reg_name == "Greater London" ~ "London",
                              reg_name == "Yorkshire and the Humber" ~ "Yorkshire and The Humber",
                              TRUE ~ reg_name))

hex24 <- st_read(here("data","boundaries","hexConstituencies.json"), quiet = TRUE) |> 
  select(PCON24CD,PCON24NM,name3,regionNM,geometry) |> 
  rename(con_name = PCON24NM,
         con_code = PCON24CD,
         reg_name = regionNM,
         con_abb = name3) |> 
  filter(!reg_name %in% c("Scotland","Northern Ireland","Wales")) # only England

hex_reg24 <- hex24 |> 
  ms_dissolve("reg_name")

# 2024 votes
votes24 <- read.csv(here("data","results","HoC-GE2024-results-by-constituency.csv")) |> 
  clean_names() |> 
  left_join(constituencies24 |> select(con_code,con_abb,geometry),
            by = c("ons_id"="con_code")) |> 
  filter(country_name == "England") |>  # only England
  rename(con_code = ons_id) |> 
  mutate(other = green + all_other_candidates,
         first_party = tolower(first_party),
         second_party = tolower(second_party)) |> 
  select(con_code,constituency_name,region_name,first_party,second_party,con,lab,ld,ruk,other,valid_votes,majority,geometry) |> 
  rename(first_party24 = first_party,
         second_party24= second_party) |> 
  rowwise() |> 
  mutate(
    third_party24 = colnames(across(con:other))[order(-c_across(con:other))[3]]
  ) |> 
  ungroup() |> 
  rename(con24 = con,
         lab24 = lab,
         ld24 = ld,
         ruk24 = ruk,
         other24 = other,
         valid_votes24 = valid_votes,
         majority24 = majority) |>
  mutate(con24_pct = 100*con24/valid_votes24,
         lab24_pct = 100*lab24/valid_votes24,
         ld24_pct = 100*ld24/valid_votes24,
         ruk24_pct = 100*ruk24/valid_votes24,
         other24_pct = 100*other24/valid_votes24) |> 
  st_as_sf()


```

### Census data

```{r, echo=FALSE}
sex_age <- readxl::read_xlsx(here("data","census21","RM121-Sex-By-Age-2021-p19wpc-ONS.xlsx")) |> 
  clean_names() |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies,
           age_23_categories_code,
           age_23_categories) |> 
  summarise(observation = sum(observation))

population <- sex_age |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(pop_tot = sum(observation))

sixteenplus <- sex_age |> 
  filter(age_23_categories_code > 6) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(sixteenplus_tot = sum(observation))

eighteenplus <- sex_age |> 
  filter(age_23_categories_code > 7) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(eighteenplus_tot = sum(observation))

over65 <- sex_age |> 
  filter(age_23_categories_code > 18) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(over65_tot = sum(observation))


education <- readxl::read_xlsx(here("data","census21","TS067-Highest-Level-Of-Qualification-2021-p19wpc-ONS.xlsx")) |> 
  clean_names()
education <- education[education[,3] == "5",] |> 
  rename(degree_tot = observation) |> 
  select(1,2,degree_tot)

disability <- readxl::read_xlsx(here("data","census21","TS038-Disability-2021-p19wpc-ONS.xlsx")) |> 
  clean_names()
# disability <- disability[disability[,3] == 1 | disability[,3] == 2,] |>  # limited a little or a lot
disability <- disability[disability[,3] == 1,] |> # limited a lot
  rename(disability_tot = observation) |> 
  select(1,2,disability_tot) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(disability_tot = sum(disability_tot))

health <- readxl::read_xlsx(here("data","census21","RM044-General-Health-By-Ns-Sec-2021-p19wpc-ONS.xlsx")) |> 
  clean_names()
health <- health[health[,3] == "3" | health[,3] == "4" | health[,3] == "5",] |> 
  rename(notgoodhealth_tot = observation) |> 
  select(1,2,notgoodhealth_tot) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(notgoodhealth_tot = sum(notgoodhealth_tot))

white <- readxl::read_xlsx(here("data","census21","RM087-National-Identity-By-Ethnic-Group-2021-p19wpc-ONS.xlsx")) |> 
  clean_names()
white <- white |> 
  filter(str_detect(ethnic_group_8_categories, "White")) |> 
  rename(white_tot = observation) |> 
  select(1,2,white_tot) |> 
  group_by(post_2019_westminster_parliamentary_constituencies_code,
           post_2019_westminster_parliamentary_constituencies) |> 
  summarise(white_tot = sum(white_tot))


census <- population |> 
  left_join(sixteenplus) |> 
  left_join(eighteenplus) |> 
  left_join(over65) |> 
  mutate(over65 = over65_tot / pop_tot) |> 
  left_join(education) |> 
  mutate(degree = degree_tot / eighteenplus_tot) |> 
  left_join(disability) |> 
  mutate(disability = disability_tot / pop_tot) |> 
  left_join(health) |> 
  mutate(notgoodhealth = notgoodhealth_tot / pop_tot) |> 
  left_join(white) |> 
  mutate(white = white_tot / pop_tot) |> 
  rename(con_code = post_2019_westminster_parliamentary_constituencies_code) |> 
  select(con_code, over65, degree, notgoodhealth, white, pop_tot)

```


### Unite into one data frame

```{r, echo=FALSE}
df <- votes24 |> 
  left_join(votes19proj, by="con_code") |> 
  left_join(votes17proj, by="con_code") |> 
  left_join(census, by="con_code") |> 
  mutate(thousand_perkm = (pop_tot/1000) / units::set_units(st_area(geometry), km^2)) |> 
  st_as_sf() |> 
  select(-pop_tot) |> 
  select(con_code, region_name, constituency_name, first_party24 ,second_party24, third_party24, everything(), -geometry) |> 
  select(everything(), geometry) |> 
  filter(constituency_name != "Chorley")

df$region_name <- factor(df$region_name)
df$density <- df$thousand_perkm |> as.numeric()

dfhex <- df |> 
  st_drop_geometry() |> 
  left_join(hex24, by="con_code") |> 
  st_as_sf()

```

### LibDem nb

```{r}
# matrix version of nb df for stan:
dfnbld <- st_bridges(df[df$ld24!=0,], "constituency_name", nb_structure = "matrix") |> 
  st_force_join_nb("Isle of Wight East","Gosport") |> 
  st_force_join_nb("Isle of Wight West","New Forest West") |> 
  mutate(first_party19 = factor(first_party19,
                                levels=c("ld","lab","con","other")),
         second_party19 = factor(second_party19,
                                levels=c("ld","lab","con","ruk","other")),
         third_party19 = factor(third_party19,
                                levels=c("ld","lab","con","ruk","other")),
         majority_prop = majority19/valid_votes19,
         majority_prop_scale = as.numeric(scale(majority19/valid_votes19)),
         degree_scale = as.numeric(scale(degree)),
         notgoodhealth_scale = as.numeric(scale(notgoodhealth)),
         white_scale = as.numeric(scale(white))) |> 
  mutate(second_party19comp = case_when(second_party19 == "ruk" ~ "other/ruk",
                                        second_party19 == "other" ~ "other/ruk",
                                        TRUE ~ second_party19),
         second_party19comp = factor(second_party19comp,
                                levels=c("ld","lab","con","other/ruk")))

```

### Con nb

```{r}

# matrix version of nb df for stan:
dfnbcon <- st_bridges(df[df$con24!=0,], "constituency_name", nb_structure = "matrix") |> 
  st_force_join_nb("Isle of Wight East","Gosport") |> 
  st_force_join_nb("Isle of Wight West","New Forest West") |> 
  mutate(first_party19 = factor(first_party19,
                                levels=c("con","lab","ld","other")),
         second_party19 = factor(second_party19,
                                levels=c("con","lab","ld","ruk","other")),
         third_party19 = factor(third_party19,
                                levels=c("con","lab","ld","ruk","other")),
         majority_prop = majority19/valid_votes19,
         majority_prop_scale = as.numeric(scale(majority19/valid_votes19)),
         degree_scale = as.numeric(scale(degree)),
         notgoodhealth_scale = as.numeric(scale(notgoodhealth)),
         white_scale = as.numeric(scale(white))) |> 
  mutate(second_party19comp = case_when(second_party19 == "ruk" ~ "other/ruk",
                                        second_party19 == "other" ~ "other/ruk",
                                        TRUE ~ second_party19),
         second_party19comp = factor(second_party19comp,
                                levels=c("con","lab","ld","other/ruk")))


```

### Lab nb

```{r}

# matrix version of nb df for stan:
dfnblab <- st_bridges(df[df$lab24!=0,], "constituency_name", nb_structure = "matrix") |> 
  # st_force_join_nb("St Ives","Truro and Falmouth") |>
  # st_force_join_nb("St Ives","Camborne and Redruth") |>
  # st_force_join_nb("Truro and Falmouth","North Cornwall") |>
  # st_force_join_nb("Truro and Falmouth","St Austell and Newquay") |>
  st_force_join_nb("Isle of Wight East","Gosport") |> 
  st_force_join_nb("Isle of Wight West","New Forest West") |> 
  mutate(first_party19 = factor(first_party19,
                                levels=c("lab","con","ld","other")),
         second_party19 = factor(second_party19,
                                levels=c("lab","con","ld","ruk","other")),
         third_party19 = factor(third_party19,
                                levels=c("lab","con","ld","ruk","other")),
         majority_prop = majority19/valid_votes19,
         majority_prop_scale = as.numeric(scale(majority19/valid_votes19)),
         degree_scale = as.numeric(scale(degree)),
         notgoodhealth_scale = as.numeric(scale(notgoodhealth)),
         white_scale = as.numeric(scale(white))) |> 
  mutate(second_party19comp = case_when(second_party19 == "ruk" ~ "other/ruk",
                                        second_party19 == "other" ~ "other/ruk",
                                        TRUE ~ second_party19),
         second_party19comp = factor(second_party19comp,
                                levels=c("lab","con","ld","other/ruk")))

```

### Reform nb

```{r}

# matrix version of nb df for stan:
dfnbruk <- st_bridges(df[df$ruk24!=0,], "constituency_name", nb_structure = "matrix") |> 
  # st_force_join_nb("St Ives","Truro and Falmouth") |>
  # st_force_join_nb("St Ives","Camborne and Redruth") |>
  # st_force_join_nb("Truro and Falmouth","North Cornwall") |>
  # st_force_join_nb("Truro and Falmouth","St Austell and Newquay") |>
  st_force_join_nb("Isle of Wight East","Gosport") |> 
  st_force_join_nb("Isle of Wight West","New Forest West") |> 
  mutate(first_party19 = factor(first_party19,
                                levels=c("lab","con","ld","other")),
         second_party19 = factor(second_party19,
                                levels=c("ruk","lab","con","ld","other")),
         third_party19 = factor(third_party19,
                                levels=c("ruk","lab","con","ld","other")),
         majority_prop = majority19/valid_votes19,
         majority_prop_scale = as.numeric(scale(majority19/valid_votes19)),
         degree_scale = as.numeric(scale(degree)),
         notgoodhealth_scale = as.numeric(scale(notgoodhealth)),
         white_scale = as.numeric(scale(white))) |> 
  mutate(second_party19comp = case_when(second_party19 == "ruk" ~ "other/ruk",
                                        second_party19 == "other" ~ "other/ruk",
                                        TRUE ~ second_party19),
         second_party19comp = factor(second_party19comp,
                                levels=c("other/ruk","lab","con","ld")))

```

## Priors

```{r}
priors <- c(
  prior(normal(0, 10), class = "Intercept"),
  prior(normal(0, 10), class = "b")
)
```

## LibDem model

```{r}

W <- dfnbld$nb

library(cmdstanr)
library(brms)
options(brms.backend = "cmdstanr")

# mod5_ld <- brm(ld24 ~ first_party19 + second_party19comp * majority_prop_scale +
#                  degree_scale + notgoodhealth_scale + white_scale + region_name +
#                  car(W, gr=constituency_name, type = "icar") +
#                  offset(log(valid_votes24)),
#                data=dfnbld,
#                data2 = list(W = W),
#                family = poisson(),
#                chains = 4,
#                warmup = 1000,
#                iter = 70000,
#                cores = 4,
#                seed = 12345,
#                backend = "cmdstanr",
#                threads = threading(2),
#                prior = priors,
#                thin = 10,
#                control = list(adapt_delta = 0.99,
#                               max_treedepth = 14),
#                file = NULL,
#                save_pars = save_pars(all = TRUE))
# 
# saveRDS(mod5_ld, here("mods24","mods_ld","mod5_ld.rds"))

mod5_ld <- readRDS(here("mods24","mods_ld","mod5_ld.rds"))

summary_mod5_ld <- summary(mod5_ld)

# margloglik_mod5_ld <- bridge_sampler(mod5_ld)
# saveRDS(margloglik_mod5_ld, here("mods24","mods_ld","margloglik_mod5_ld.rds"))

margloglik_mod5_ld <- readRDS(here("mods24","mods_ld","margloglik_mod5_ld.rds"))

```

## Conservative model

```{r}

W <- dfnbcon$nb

# library(cmdstanr)
library(brms)
options(brms.backend = "cmdstanr")

# mod5_con <- brm(con24 ~ first_party19 + second_party19comp * majority_prop_scale +
#                   degree_scale + notgoodhealth_scale + white_scale + region_name +
#                   car(W, gr=constituency_name, type = "icar") +
#                   offset(log(valid_votes24)),
#                 data=dfnbcon,
#                 data2 = list(W = W),
#                 family = poisson(),
#                 chains = 4,
#                 warmup = 1000,
#                 iter = 70000,
#                 cores = 4,
#                 seed = 12345,
#                 backend = "cmdstanr",
#                 threads = threading(2),
#                 prior = priors,
#                 thin = 10,
#                 control = list(adapt_delta = 0.99,
#                                max_treedepth = 12),
#                 file = NULL,
#                 save_pars = save_pars(all = TRUE))
# 
# saveRDS(mod5_con, here("mods24","mods_con","mod5_con.rds"))

mod5_con <- readRDS(here("mods24","mods_con","mod5_con.rds"))

summary_mod5_con <- summary(mod5_con)

# margloglik_mod5_con <- bridge_sampler(mod5_con)
# saveRDS(margloglik_mod5_con, here("mods24","mods_con","margloglik_mod5_con.rds"))

margloglik_mod5_con <- readRDS(here("mods24","mods_con","margloglik_mod5_con.rds"))

```

## Labour model

```{r}

W <- dfnblab$nb

# mod5_lab <- brm(lab24 ~ first_party19 + second_party19comp * majority_prop_scale +
#                   degree_scale + notgoodhealth_scale + white_scale + region_name +
#                   car(W, gr=constituency_name, type = "icar") +
#                   offset(log(valid_votes24)),
#                 data=dfnblab,
#                 data2 = list(W = W),
#                 family = poisson(),
#                 chains = 4,
#                 warmup = 1000,
#                 iter = 70000,
#                 cores = 4,
#                 seed = 12345,
#                 backend = "cmdstanr",
#                 threads = threading(2),
#                 prior = priors,
#                 thin = 10,
#                 control = list(adapt_delta = 0.99,
#                                max_treedepth = 14),
#                 file = NULL,
#                 save_pars = save_pars(all = TRUE))
# 
# saveRDS(mod5_lab, here("mods24","mods_lab","mod5_lab.rds"))

mod5_lab <- readRDS(here("mods24","mods_lab","mod5_lab.rds"))

summary_mod5_lab <- summary(mod5_lab)

# margloglik_mod5_lab <- bridge_sampler(mod5_lab)
# saveRDS(margloglik_mod5_lab, here("mods24","mods_lab","margloglik_mod5_lab.rds"))

margloglik_mod5_lab <- readRDS(here("mods24","mods_lab","margloglik_mod5_lab.rds"))

```

## Reform UK model

```{r}

W <- dfnbruk$nb

# mod5_ruk <- brm(ruk24 ~ first_party19 + second_party19comp * majority_prop_scale +
#                   degree_scale + notgoodhealth_scale + white_scale + region_name +
#                   car(W, gr=constituency_name, type = "icar") +
#                   offset(log(valid_votes24)),
#                 data=dfnbruk,
#                 data2 = list(W = W),
#                 family = poisson(),
#                 chains = 4,
#                 warmup = 1000,
#                 iter = 70000,
#                 cores = 4,
#                 seed = 12345,
#                 backend = "cmdstanr",
#                 threads = threading(2),
#                 prior = priors,
#                 thin = 10,
#                 control = list(adapt_delta = 0.99,
#                                max_treedepth = 14),
#                 file = NULL,
#                 save_pars = save_pars(all = TRUE))
# 
# saveRDS(mod5_ruk, here("mods24","mods_ruk","mod5_ruk.rds"))

mod5_ruk <- readRDS(here("mods24","mods_ruk","mod5_ruk.rds"))

summary_mod5_ruk <- summary(mod5_ruk)

# margloglik_mod5_ruk <- bridge_sampler(mod5_ruk)
# saveRDS(margloglik_mod5_ruk, here("mods24","mods_ruk","margloglik_mod5_ruk.rds"))

margloglik_mod5_ruk <- readRDS(here("mods24","mods_ruk","margloglik_mod5_ruk.rds"))

```














